import fp from 'fastify-plugin'
import { RouteCommonOptions } from 'types/routesCommon'
import { dashboardConcertSchemas, createConcertBody, updateConcertBody } from './schema'
import { ADMIN_ROOT } from 'schemas/user'
import { FastifyReply, FastifyRequest } from 'fastify'
import { Pagination } from 'types/pagination'

export const dashboardConcertRotues = fp((fastify, options: RouteCommonOptions) => {
	fastify.route({
		method: 'GET',
		url: `${options.prefix}`,
		schema: dashboardConcertSchemas.concertList,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: getConcertList
	})
	async function getConcertList(req: FastifyRequest<{ Querystring: Pagination }>, reply: FastifyReply) {
		const concerts = await fastify.prismaW.concert.findMany({
			skip: req.query.offset,
			take: req.query.size,
			include: {
				tickets: true
			}
		})
		const concerts2 = await Promise.all(
			concerts.map((c) => c.withPopulatedFields())
		)

		reply.status(200).send(concerts2)
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}`,
		schema: dashboardConcertSchemas.createConcert,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: createConcert
	})
	async function createConcert(
		req: FastifyRequest<{ Body: createConcertBody }>,
		reply: FastifyReply
	) {
		const { groupSlugs, categorySlugs, ...concertData } = req.body

		const groupIds = groupSlugs && groupSlugs.length
			? await fastify.prisma.musicGroup.findMany({
				where: { 
					slug: { in: groupSlugs } 
				},
				select: {
					id: true
				}
			}).then((musicGroup) => musicGroup.map((m) => m.id))
			: undefined

		const categoryIds = categorySlugs && categorySlugs.length
			? await fastify.prisma.category.findMany({
				where: { 
					slug: { in: categorySlugs } 
				},
				select: { 
					id: true 
				}
			}).then(categories => categories.map(c => c.id))
			: undefined
		
		const concert = await fastify.prismaW.concert.create({ 
			data: {
				...concertData,
				slug: '', // auto generated by prisma extension
				groups: groupIds,
				categories: categoryIds,
				comments: []
			}
		})

		if(concert.isActive && concert.status === 'ACCEPTED') {
			await fastify.prisma.concertEmbeddings.create({
				data: {
					concertId: concert.id,
					title: concert.title,
					description: concert.description,
					locationName: concert.locationName,
					embedding: await concert.getEmbeddings()
				}
			})
		}


		reply.status(201).send(await concert.withPopulatedFields())
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}/:slug`,
		schema: dashboardConcertSchemas.updateConcert,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: updateConcert
	})
	async function updateConcert(
		req: FastifyRequest<{ Params: { slug: string }, Body: updateConcertBody }>,
		reply: FastifyReply
	) {
		const { slug } = req.params
		const { groupSlugs, categorySlugs, ...updateData } = req.body
				
		const groupIds = groupSlugs && groupSlugs.length
			? await fastify.prisma.musicGroup.findMany({
				where: { 
					slug: { in: groupSlugs } 
				},
				select: {
					id: true
				}
			}).then((musicGroup) => musicGroup.map((m) => m.id))
			: undefined

		const categoryIds = categorySlugs && categorySlugs.length
			? await fastify.prisma.category.findMany({
				where: { 
					slug: { in: categorySlugs } 
				},
				select: { 
					id: true 
				}
			}).then(categories => categories.map(c => c.id))
			: undefined
		
		const concert = await fastify.prismaW.concert.update({ 
			where: { slug }, 
			data: {
				...updateData,
				categories: categoryIds,
				groups: groupIds
			}
		})

		if(concert.isActive && concert.status === 'ACCEPTED') {
			await fastify.prisma.concertEmbeddings.upsert({
				create: {
					concertId: concert.id,
					title: concert.title,
					description: concert.description,
					locationName: concert.locationName,
					embedding: await concert.getEmbeddings(),
				},
				update: {
					title: concert.title,
					description: concert.description,
					locationName: concert.locationName,
					embedding: await concert.getEmbeddings()
				},
				where: {
					concertId: concert.id
				}
			})
		} else {
			await fastify.prisma.concertEmbeddings.deleteMany({
				where: {
					concertId: concert.id
				}
			})
		}

		reply.status(200).send(await concert.withPopulatedFields())
	}

	fastify.route({
		method: 'DELETE',
		url: `${options.prefix}/:slug`,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: deleteConcert
	})
	async function deleteConcert(req: FastifyRequest<{ Params: { slug: string } }>, reply: FastifyReply) {
		const { slug } = req.params

		const concert = await fastify.prismaW.concert.delete({
			where: { slug } 
		})

		await fastify.prisma.concertEmbeddings.deleteMany({
			where: {
				concertId : concert.id
			}
		})

		reply.status(204).send()
	}
})