import fp from 'fastify-plugin'
import { RouteCommonOptions } from 'types/routesCommon'
import { dashboardConcertSchemas, createConcertBody, updateConcertBody } from './schema'
import { ADMIN_ROOT } from 'schemas/user'
import { FastifyReply, FastifyRequest } from 'fastify'
import { Pagination } from 'types/pagination'

export const dashboardConcertRotues = fp((fastify, options: RouteCommonOptions) => {
	fastify.route({
		method: 'GET',
		url: `${options.prefix}`,
		schema: dashboardConcertSchemas.concertList,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: getConcertList
	})
	async function getConcertList(req: FastifyRequest<{ Querystring: Pagination }>, reply: FastifyReply) {
		const concerts = await fastify.prismaW.concert.findMany({
			skip: req.query.offset,
			take: req.query.size
		})

		reply.status(200).send(concerts)
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}`,
		schema: dashboardConcertSchemas.createConcert,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: createConcert
	})
	async function createConcert(
		req: FastifyRequest<{ Body: createConcertBody }>,
		reply: FastifyReply
	) {
		const { groupSlugs, categorySlugs, ...concertData } = req.body
		
		// Convert slugs to IDs
		let groupIds: string[] = []
		let categoryIds: string[] = []
		
		if (groupSlugs && groupSlugs.length > 0) {
			const groups = await fastify.prisma.musicGroup.findMany({
				where: { slug: { in: groupSlugs } },
				select: { id: true }
			})
			groupIds = groups.map(g => g.id)
		}
		
		if (categorySlugs && categorySlugs.length > 0) {
			const categories = await fastify.prisma.category.findMany({
				where: { slug: { in: categorySlugs } },
				select: { id: true }
			})
			categoryIds = categories.map(c => c.id)
		}
		
		const concert = await fastify.prismaW.concert.create({ 
			data: {
				...concertData,
				slug: '', // auto generated by prisma extension
				groups: groupIds,
				categoroies: categoryIds,
				comments: []
			}
		})
        
		reply.status(201).send(concert)
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}/:slug`,
		schema: dashboardConcertSchemas.updateConcert,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: updateConcert
	})
	async function updateConcert(
		req: FastifyRequest<{ Params: { slug: string }, Body: updateConcertBody }>,
		reply: FastifyReply
	) {
		const { slug } = req.params
		const { groupSlugs, categorySlugs, ...updateData } = req.body
		
		// Convert slugs to IDs if provided
		const dataToUpdate: any = { ...updateData }
		
		if (groupSlugs !== undefined) {
			if (groupSlugs.length > 0) {
				const groups = await fastify.prisma.musicGroup.findMany({
					where: { slug: { in: groupSlugs } },
					select: { id: true }
				})
				dataToUpdate.groups = groups.map(g => g.id)
			} else {
				dataToUpdate.groups = []
			}
		}
		
		if (categorySlugs !== undefined) {
			if (categorySlugs.length > 0) {
				const categories = await fastify.prisma.category.findMany({
					where: { slug: { in: categorySlugs } },
					select: { id: true }
				})
				dataToUpdate.categoroies = categories.map(c => c.id)
			} else {
				dataToUpdate.categoroies = []
			}
		}
		
		const concert = await fastify.prismaW.concert.update({ 
			where: { slug }, 
			data: dataToUpdate
		})

		reply.status(200).send(concert)
	}

	fastify.route({
		method: 'DELETE',
		url: `${options.prefix}/:slug`,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: deleteConcert
	})
	async function deleteConcert(req: FastifyRequest<{ Params: { slug: string } }>, reply: FastifyReply) {
		const { slug } = req.params

		await fastify.prismaW.concert.delete({
			where: { slug } 
		})
		reply.status(204).send()
	}
})