import fp from 'fastify-plugin'
import { RouteCommonOptions } from 'types/routesCommon'
import { dashboardCategoriesSchemas, createCategoryBody, updateCategoryBody } from './schema'
import { ADMIN_ROOT } from 'schemas/user'
import { FastifyReply, FastifyRequest } from 'fastify'
import { Pagination } from 'types/pagination'

export const dashboardCategoriesRoutes = fp((fastify, options: RouteCommonOptions) => {
	fastify.route({
		method: 'GET',
		url: `${options.prefix}`,
		schema: dashboardCategoriesSchemas.categoryList,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: getCategoryList
	})
	async function getCategoryList(req: FastifyRequest<{ Querystring: Pagination }>, reply: FastifyReply) {
		const categories = await fastify.prismaW.category.findMany({
			skip: req.query.offset,
			take: req.query.size
		})

		const resp = await Promise.all(
			categories.map(c => c.withConcertsLength())
		)
		reply.status(200).send(resp)
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}`,
		schema: dashboardCategoriesSchemas.createCategory,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: createCategory
	})
	async function createCategory(
		req: FastifyRequest<{ Body: createCategoryBody }>,
		reply: FastifyReply
	) {
		const category = await fastify.prismaW.category.create({ 
			data: {
				...req.body,
				slug: '', // auto generated by prisma extension
			}
		})
        
		reply.status(201).send({ ...category, concerts: 0 })
	}

	fastify.route({
		method: 'POST',
		url: `${options.prefix}/:slug`,
		schema: dashboardCategoriesSchemas.updateCategory,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: updateCategory
	})
	async function updateCategory(
		req: FastifyRequest<{ Params: { slug: string }, Body: updateCategoryBody }>,
		reply: FastifyReply
	) {
		const { slug } = req.params
		const category = await fastify.prismaW.category.update({ 
			where: { slug }, 
			data: req.body 
		})

		reply.status(200).send(await category.withConcertsLength())
	}

	fastify.route({
		method: 'DELETE',
		url: `${options.prefix}/:slug`,
		onRequest: [fastify.authenticate(ADMIN_ROOT)],
		handler: deleteCategory
	})
	async function deleteCategory(req: FastifyRequest<{ Params: { slug: string } }>, reply: FastifyReply) {
		const { slug } = req.params

		await fastify.prismaW.category.delete({
			where: { slug } 
		})
		reply.status(204).send()
	}
})